[package]
org = "ballerinax"
name = "health.hl7v251"
version = "1.0.3-snapshot"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.5.1"]
distribution = "2201.5.0"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "1.0.5"